qdrant:
  url: http://localhost:6333
  api_key: "qdrjYgmlPGcjGgybJmEPEJvFOoQ9hdkjDcP"

scrapers:
  - name: mof
    module: src.scrapers.mof
    class: MOFScraper
    start_urls:
      - "https://www.mof.gov.my/portal/en/news/press-release"
    selectors:
      listing_links: "a"

  - name: mof-archive
    module: src.scrapers.mof
    class: MOFScraper
    start_urls:
      - "https://www.mof.gov.my/portal/en/archive3/press-release"
    pagination:
      type: query_param
      param: "start"
      start: 5
      stop: 55
      step: 5
    selectors:
      listing_links: "a"


  - name: miti
    module: src.scrapers.miti
    class: MITIScraper
    start_urls:
      - "https://www.miti.gov.my/miti/resources/Media%20Release/BELANJAWAN_2026_MITI_Penerusan_Transformasi_Industri_bagi_Kelangsungan_Industri-PKS-Rakyat_2025-10-11.pdf"
    selectors:
      listing_links: "a"
      

  - name: bnm
    module: src.scrapers.bnm
    start_urls:
      - "https://www.bnm.gov.my/press-release-2025"
    selectors:
      listing_links: "a"

user_agent: "gov-scraper-bot/1.0 (+https://axelyn.com)"
concurrency: 4